### ISSUE TITLE
Add all Exotic Executioner mobs into list

### ISSUE THREAD

**Issue by lainverse** [NekoNova/RareTracker#11]
I made a list to make it easier. However, I typed it myself, so it's better to check them.
Adding them all manually is a real pain since all the changes disappear right after the re-login.

Exotic:
Bot Pulverizer LD-17
Tuskar the Shatterhorn
Glacierjaw
Frozenclaw
Sleethide
Soragh Silvertooth
X426 Augmentor Apex
Maw the Junglestalker
Vitala the Overgrown
Velum the Overgrown
Greva the Bone Collector
Viceclaw the Skinlasher
Othrum the Windlasher
Magthar the Meteorborn
Pharos the Immolator
Cz-5 Exobreaker
Nauticus the Abyssal
Cerebros
Welskar the Wild
Ersa the Soulrender
Dara the Bladekeeper
Kalsha the Life-Sworn
Kelvia the Slavemaster
Backwash the Brackish
The Primal Destroyer
Vileblossom the Putrid
Malfeast the Unclean
Grimtangle the Weaver
Tecton the Immovable
Demonpaw
Skunkh the Penalizer
Snerf the Bloodnose
Alex "Stabby" Boyer
Skawren the Gale Witch
Sun-Holder
Ragestone
Bloodtusk
Bloodpaw
Worg the Mind Corruptor
Kedrik the Crazed
Verok the Insane
X21 Goliath
D23 Titan
Tremgut
Zeke the Anguished
Devan the Disturbed
Crispin the Tormented
Malmedical Mechanica
Pyropaw the Smokey
Aranea
Shatterback
Tidebreaker Sorlek
Spinebreaker Brukah
Frubb the Grotesque
Grodga the Wicked
Freezia
Freygoth
Frethalem
Fregad

Apex life forms: - not sure if these are needed, but they were in a separate list in one of the achievements
Abominus
Skalgoth the Coldhearted
Uth Kundar
Nashdul the Unchained
Ghost
Morthun the Shieldbreaker
Frost-Keeper Arcanist
Malfunctioning Unit "GL-4C13R"

**Comment by coding-red-panda** [comment]
thank you very much.
I will add these to the EN list and check them out, then try to get them translated for DE and FR.

**Comment by coding-red-panda** [comment]
All tracked in version 2.2, you can see it in the open pull-request.
Going to close this for now
