### ISSUE TITLE
Feature Request: Option to disable notification for already killed rares

### ISSUE THREAD

**Issue by Mihari** [NekoNova/RareTracker#4]
Requesting a feature to disable notifications for rares that have already been killed, IE for those solely killing once for achievement(s).

**Comment by coding-red-panda** [comment]
I see two possibilities here.
Lazy mode where it simply tracks kills, and doesn't pop it up again when already killed.
Or more advanced, parsing the achievements for killing rares, and keeping track of those achievements earned, not popping up the mob name if the achievement has been granted.

bool toggle then to enable to disable this.

**Comment by Mihari** [comment]
Well I do know it already parses the achievements for rares, since it displays them in the config list... but I think you'd know better in which case would perform better with less overhead.

**Comment by lainverse** [comment]
Um... They already marked as killed in the config list. It would be nice to at least show them with the mark when they pop-up if hiding them is a problem. Either hiding or marking as already killed (as in the config) would be nice.

**Comment by coding-red-panda** [comment]
Will look into that. If they are tracked in the killed list, I should be able to pass that info around.

**Comment by coding-red-panda** [comment]
implementation idea : 

I will add the same Icon on the popup, showing that you already killed it.
I will retain all other functionality as it, cause You still might want to track down killed mobs for friends or buffs/gear

**Comment by coding-red-panda** [comment]
- [ ] Extend `BuildAchievementList` to include all tracking achievements
- [ ] Use `self.achievementEntries` to check whether a mob has been killed
- [ ] Add the Icon to the popup item
- [ ] Toggle the Icon based on the boolean value of `self.achievementsEntries[mobName]`
- [ ] trigger `BuildAchievementList` every time a rare mob is found
- [ ] Add boolean value to disable tracking of killed mobs
- [ ] Implement the kill check on the `UnitCreated` event

**Comment by lainverse** [comment]
Um... What about an option in config to either mark or hide? Usually I don't want to see them at all, but I do agree it should be in the "mark" mode by default.

**Comment by coding-red-panda** [comment]
Will add that as well in the config, simply tracking  boolean state.
So I will combine both:

config option : don't track killed mobs
When set to true, an already killed mob will not be tracked

**Comment by coding-red-panda** [comment]
This feature has been implemented in 2.2, you can check it out in the new branch/pull-request.
By default RareTracker is NOT going to track killed mobs anymore. You can change this in the options of raretracker.

Just waiting on Carbine to give me the propery french achievement names to track and we're good to go.
