### ISSUE TITLE
Settings

### ISSUE THREAD

**Issue by Sephirox** [NekoNova/RareTracker#5]
Addon is not saving position when reloging.

**Comment by coding-red-panda** [comment]
Not sure if that was originally supported with RareTracker, will look into it.

**Comment by Sephirox** [comment]
Pretty sure it saved its position before drop6? Then again might be some of thhe things Carbino change thats causing some addons to forget their position.

Sincerely,

Juan Alvarez

**Comment by coding-red-panda** [comment]
there's a lot of stuff that caused RareTracker to not work properly anymore....
I might even have to rewrite it to fix most issues, but I will see what i can do.

**Comment by Sephirox** [comment]
I see, Well I don't use it that much anymore. And since they change how Rare mobs work its pretty much in a weird state now, so don't fret over it. There is prob other addons more important as of now that might need some work.

Thanks anyways!

Sincerely,

Juan Alvarez

**Comment by coding-red-panda** [comment]
Can you please check if it works properly now in v2.0.0 of RareTracker ?

**Comment by Sephirox** [comment]
Still not saving its position, also there are several instances of the addon running on my addon log.

**Comment by coding-red-panda** [comment]
Then I need to look into Carbine Addons that work and see how they do it.
Will try playing around with the code more.

**Comment by Sephirox** [comment]
Seems its not appearing in the Interface window to lock it, might be to add the new Window management thing?

**Comment by coding-red-panda** [comment]
v2.0.1 should store positions now. Tested it locally and it persisted through /reloadui calls for me
I'm using the code for the window management thing, but not sure how it works properly.

**Comment by coding-red-panda** [comment]
Sephirox,
Is the addon now properly storing Windows positions?

**Comment by Sephirox** [comment]
Yes, thanks!!

Sincerely,

Juan Alvarez
