### ISSUE TITLE
RareTracker

### ISSUE THREAD

**Issue by Sephirox** [NekoNova/RareTracker#6]
Seems now there is 3 instances of the addon running, two which are disabled.

**Comment by coding-red-panda** [comment]
checking

**Comment by coding-red-panda** [comment]
![Addons](http://i.imgur.com/ZGm6Kvc.png)
Looks fine on my side. Did you uninstall old versions and RareTrackerEx ?

**Comment by Sephirox** [comment]
Yea let me delete by hand everything and do a clean install

**Comment by Sephirox** [comment]
ok yea had to do a complete clean install, but still not saving position settings

**Comment by coding-red-panda** [comment]
Closing this one then. Windows positions tracked in #5
