### ISSUE TITLE
Random announcements "Grinder" still persists!

### ISSUE THREAD

**Issue by GreatTeacherOni** [NekoNova/RareTracker#8]
You told me i should reopen, didn't know how to do it so i just opened a new one.
It is finding the Grinder Mount that is standing on display behind the Hoverboard Flair Imports Vendor. In south of Thayd.

**Comment by coding-red-panda** [comment]
Okay, I will try to test this during the weekend and see what kind of Unit type this is and ignore it, code wise

**Comment by NekoNova** [comment]
Okay, I will try to test this during the weekend and see what kind of Unit type this is and ignore it, code wise

**Comment by coding-red-panda** [comment]
duplicate of #7
